name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: test-flow
    steps:
    - uses: actions/checkout@master
    - name: Login to ACR by uid
      uses: denverdino/acr-login@v0.1.0
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
    - name: Build and push image registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo:$IMAGE_TAG
    - name: Login to ACR with temp token
      uses: denverdino/acr-login@v0.1.0
      with:
        region-id: cn-hangzhou
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
    - name: Build and push image registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo:test .
        docker push registry.cn-hangzhou.aliyuncs.com/denverdino/nginx-demo:test
    - name: Login to ACR EE intance with temp token
      uses: denverdino/acr-login@v0.1.0
      with:
        login-server: https://acr-ee-registry.cn-hangzhou.cr.aliyuncs.com
        region-id: cn-hangzhou  
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
        instance-id: "cri-rr502bh5sa8lcmt6"
    - name: Build and push image acr-ee-registry.cn-hangzhou.cr.aliyuncs.com/test/nginx-demo
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t acr-ee-registry.cn-hangzhou.cr.aliyuncs.com/test/nginx-demo:$IMAGE_TAG .
        docker push acr-ee-registry.cn-hangzhou.cr.aliyuncs.com/test/nginx-demo:$IMAGE_TAG
    - name: Scan image in ACR
      uses: denverdino/acr-scan@v0.1.0
      with:
        region-id: cn-hangzhou  
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
        repository: "denverdino/nginx-demo"
        tag: test
    - name: Scan image in ACR EE
      uses: denverdino/acr-scan@v0.1.0
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        region-id: cn-hangzhou  
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
        instance-id: "cri-rr502bh5sa8lcmt6"
        repository: "test/nginx-demo"
        tag: $IMAGE_TAG
