name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: test-flow
    steps:
    - name: Login to ACR
      uses: denverdino/acr-login@releases/v1
      with:
        login-server: https://cr.cn-hangzhou.aliyuncs.com
        accessKeyId: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        accessKeySecret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
