name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: test-flow
    steps:
    - name: Login to ACR
      uses: denverdino/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"

