name: v1 test
on: 
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: test-flow
    env:
      IMAGE_TAG: ${{ github.sha }}
      NAMESPACE: denverdino
      IMAGE: nginx
      ACR_REGISTRY: registry.cn-hangzhou.aliyuncs.com
      ACR_EE_REGISTRY: knative-dev-registry.cn-hangzhou.cr.aliyuncs.com
      ACR_EE_INSTANCE_ID: cri-t0c5ol5s4rf6lpje
      ACR_EE_NAMESPACE: denverdino
      REGION_ID: cn-hangzhou
    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR EE instance with temp token
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://${{ env.ACR_EE_REGISTRY }}"
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
        instance-id: "${{ env.ACR_EE_INSTANCE_ID }}"
    - name: Build and push image to ACR EE instance
      run: |
        docker build -t $ACR_EE_REGISTRY/$ACR_EE_NAMESPACE/$IMAGE:test .
        docker push $ACR_EE_REGISTRY/$ACR_EE_NAMESPACE/$IMAGE:test
    - name: Scan image in ACR EE
      uses: aliyun/acr-scan@v1
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.REGISTRY_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.REGISTRY_ACCESS_KEY_SECRET }}"
        instance-id: "${{ env.ACR_EE_INSTANCE_ID }}"
        repository: "${{ env.ACR_EE_NAMESPACE}}/${{ env.IMAGE }}"
        tag: test
